name: fluxwalls
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  shared_preferences: ^2.5.4
  dio: ^5.9.1
  google_fonts: ^8.0.0
  fluttertoast: ^9.0.0
  modal_progress_hud_nsn: ^0.5.1
  internet_connection_checker_plus: ^2.9.1+2
  flutter_dotenv: ^6.0.0
  lottie: ^3.3.2
  animated_text_kit: ^4.3.0
  animations: ^2.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  device_info_plus: ^12.3.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Correct Root-Level Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#102220"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/